# Use an official OpenJDK runtime as a parent image
FROM openjdk:8-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the built JAR file to the container
COPY build/libs/get-stationid-list-by-name-list.jar /app/get-stationid-list-by-name-list.jar