FROM openjdk:8-jre-slim
WORKDIR /app
COPY ./NestedWorkflow/workflow5/01/get-left-trip-tickets/build/libs/get-left-trip-tickets.jar /app/get-left-trip-tickets.jar
COPY ./NestedWorkflow/workflow5/07/query-for-station-id-by-station-name/build/libs/query-for-station-id-by-station-name.jar /app/query-for-station-id-by-station-name.jar