# Use an official OpenJDK runtime as a parent image
FROM openjdk:8-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the built JAR file to the container
COPY NestedWorkflow/workflow5/01/get-left-trip-tickets/build/libs/get-left-trip-tickets.jar /app/get-left-trip-tickets.jar
COPY NestedWorkflow/workflow5/03/get-route-by-routeid/build/libs/get-route-by-routeid.jar /app/get-route-by-routeid.jar
COPY NestedWorkflow/workflow5/04/get-traintype-by-traintypeid/build/libs/get-traintype-by-traintypeid.jar /app/get-traintype-by-traintypeid.jar
COPY NestedWorkflow/workflow5/07/query-for-station-id-by-station-name/build/libs/query-for-station-id-by-station-name.jar /app/query-for-station-id-by-station-name.jar
COPY NestedWorkflow/workflow5/08/get-left-ticket-of-interval/build/libs/get-left-ticket-of-interval.jar /app/get-left-ticket-of-interval.jar
COPY NestedWorkflow/workflow5/09/get-route-by-tripid/build/libs/get-route-by-tripid.jar /app/get-route-by-tripid.jar
COPY NestedWorkflow/workflow5/10/get-sold-tickets/build/libs/get-sold-tickets.jar /app/get-sold-tickets.jar
COPY NestedWorkflow/workflow5/11/get-traintype-by-tripid/build/libs/get-traintype-by-tripid.jar /app/get-traintype-by-tripid.jar
COPY NestedWorkflow/workflow5/12/query-config-entity-by-config-name/build/libs/query-config-entity-by-config-name.jar /app/query-config-entity-by-config-name.jar